/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EDQ91E1zuzK
 */
import Image from "next/image";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";

export function Component() {
  return (
    <div className="container mx-auto px-4">
      <section className="mb-10">
        <h2 className="mb-4 text-2xl font-bold">Personal Information</h2>
        <div className="flex items-center space-x-4">
          <Image
            alt="Profile Photo"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <div>
            <h3 className="text-xl font-semibold">John Doe</h3>
            <p className="text-sm">
              Experienced Software Engineer with a demonstrated history of
              working in the software industry.
            </p>
          </div>
        </div>
      </section>
      <section className="mb-10">
        <h2 className="mb-4 text-2xl font-bold">Education</h2>
        <div>
          <h3 className="text-lg font-semibold">Master of Computer Science</h3>
          <p className="text-sm">Stanford University, 2020-2022</p>
        </div>
        <div className="mt-4">
          <h3 className="text-lg font-semibold">
            Bachelor of Computer Science
          </h3>
          <p className="text-sm">
            University of California, Berkeley, 2016-2020
          </p>
        </div>
      </section>
      <section className="mb-10">
        <h2 className="mb-4 text-2xl font-bold">Work Experience</h2>
        <div>
          <h3 className="text-lg font-semibold">Software Engineer</h3>
          <p className="text-sm">Google, Inc., 2022-Present</p>
          <p className="text-sm">
            Developed and maintained high-traffic web applications using ReactJS
            and Node.js.
          </p>
        </div>
        <div className="mt-4">
          <h3 className="text-lg font-semibold">Junior Software Engineer</h3>
          <p className="text-sm">Facebook, Inc., 2020-2022</p>
          <p className="text-sm">
            Assisted in the development of key features for the main platform.
          </p>
        </div>
      </section>
      <section className="mb-10">
        <h2 className="mb-4 text-2xl font-bold">Skills</h2>
        <div className="flex space-x-4">
          <Badge className="items-center" variant="outline">
            <svg
              className=" h-3.5 w-3.5 -translate-x-1"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
              <line x1="12" x2="12" y1="22" y2="15.5" />
              <polyline points="22 8.5 12 15.5 2 8.5" />
              <polyline points="2 15.5 12 8.5 22 15.5" />
              <line x1="12" x2="12" y1="2" y2="8.5" />
            </svg>
            Javascript
          </Badge>
          <Badge className="items-center" variant="outline">
            <svg
              className=" h-3.5 w-3.5 -translate-x-1"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
              <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
              <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
              <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
            </svg>
            React
          </Badge>
          <Badge className="items-center" variant="outline">
            <svg
              className=" h-3.5 w-3.5 -translate-x-1"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
              <line x1="12" x2="12" y1="22" y2="15.5" />
              <polyline points="22 8.5 12 15.5 2 8.5" />
              <polyline points="2 15.5 12 8.5 22 15.5" />
              <line x1="12" x2="12" y1="2" y2="8.5" />
            </svg>
            Node.js
          </Badge>
        </div>
      </section>
      <section>
        <h2 className="mb-4 text-2xl font-bold">Contact Information</h2>
        <p className="mb-2 text-sm">Phone: (123) 456-7890</p>
        <p className="mb-2 text-sm">Email: johndoe@example.com</p>
        <div className="flex space-x-4">
          <Link href="#">
            <svg
              className=" h-5 w-5"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
              <rect height="12" width="4" x="2" y="9" />
              <circle cx="4" cy="4" r="2" />
            </svg>
          </Link>
          <Link href="#">
            <svg
              className=" h-5 w-5"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
            </svg>
          </Link>
          <Link href="#">
            <svg
              className=" h-5 w-5"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
              <path d="M9 18c-4.51 2-5-2-7-2" />
            </svg>
          </Link>
        </div>
      </section>
    </div>
  );
}
