-- Drop Tables
DROP TABLE IF EXISTS job_resume CASCADE;
DROP TABLE IF EXISTS job_field CASCADE;
DROP TABLE IF EXISTS job CASCADE;
DROP TABLE IF EXISTS entry_field CASCADE;
DROP TABLE IF EXISTS field CASCADE;
DROP TABLE IF EXISTS section_entry CASCADE;
DROP TABLE IF EXISTS entry CASCADE;
DROP TABLE IF EXISTS resume_section CASCADE;
DROP TABLE IF EXISTS section CASCADE;
DROP TABLE IF EXISTS resume CASCADE;
DROP TABLE IF EXISTS user_title CASCADE;
DROP TABLE IF EXISTS user_link CASCADE;
DROP TABLE IF EXISTS user_address CASCADE;
DROP TABLE IF EXISTS user_email CASCADE;
DROP TABLE IF EXISTS user CASCADE;
